var greekInfo = {
	greekMyth: "\tGreek mythology follows the same guidelines as general mythology, but the people places and things are based on what was known to the Greeks at the time.  Long serpent like dragons would not have been part of Greek mythology, but giants were (possibly because of discovered mammoth skulls)!\n\n"+
	            "\tThe mythology is full of excitement!  Serpent haired women, journeys to the underworld, and half creature/half human beings are always an option to come across.  Many myths give lessons, while some just seem to be good stories",
	phaethonTitle:"Phaethon's journey across the sky",
	phaethon: "The story begins in the palace of Helios.  A place of gold and ivory, brilliant light, and filled with jewels of all kinds.  In this place it is never dark, no night existed, only light so brilliant that mortals would not be able to handle the unchanging brightness.  However, one day a mortal did approach the palace.  His name was Phaethon.  His mother had told him that his father was Helios, but he doubted the fact and so was there to ask the sun himself.  Phaethon finally reached where Helios sat and had to stop, for the brilliance of Helios's crown was so much that he could not proceed further.  Helios saw Phaethon and removed his crown so that he could look at him.  He asked why Phaethon had come, and Phaethon began to explain to him that his mother had told him he was his son, but that the other boys at school always ridiculed him for saying such things.  So he was there to find out the truth. Helios told him that he was indeed his son, and offered Phaethon anything he requested as proof (even made an oath on the river Styx so that he would have to keep it).\n\n"+
			  "Much to Helios's shagrin, Phaethon declared that he wished only to take Helios's place for a single day and drive the chariot across the sky.  Helios grew weary, knowing that it was a mistake to have offered ANYTHING the boy asked for.  He told Phaethon that he would allow it if he persisted, but that he should change his mind.  The essential climb is so steep that even the horses have trouble going up, the maximum height is to such an extent that Helios himself does not wish to look down, and the final descent is so dangerous that the sea gods often wonder how Helios makes it wihtout falling headlong to the earth.  On top of those things, the horses are so wild that no other god can even control them.  Also, there are several dangers along the journey, beasts of prey; the lion, the bull, the scorpion, and the great crab.  All of those attempt to harm the chariot and driver.  However, Phaethon would not relent and so Helios, sticking to his oath, allowed the boy to drive the chariot across the sky.\n\n"+
			  "Phaethon was proud to be driving the chariot at first.  He had no doubts in his ability to guide the horses, and no fear of any of the dangers.  Then, after the initial climb, reality set in.  The chariot began swaying back and forth, out of control.  Phaethon could hardly grip the reigns and began fearing he would be removed from the chariot.  The horses realised it was not their master at he reins and so decided they were in charge.  They did not stay on the correct path, and ran as fast as they pleased.  The horses nearly crashed into the scorpion and the crab, and at that point Phaethon nearly fainted and let the reins fall from his hands.  When the reins left his hands the horses became even more invigorated.  They climbed higher and higher, went faster and faster, and then began their descent towards the earth.  Phaethon could not hold on, but was simply stuck in the chariot.  The descent was so fast that the world began to catch fire. Starting with the heighest mountains, everything began to become engulfed in flames.  Phaethon, too, was catching fire.  His body ablaze as the chariot descended ever quicker.  The gods saw this and knew if they did not take action the world would be destroyed.\n\n"+
			  "It was at that point Jove (Jupiter/Zeus)[a] threw a thunderbolt, killing Phaethon, shattering the chariot, and causing the horses to rush into the sea.  Phaethon fell from the chariot, on fire, and landed in the river Eridanus.  The naiads found his body and took pity on him, burying him with an inscription, '...Greatly he failed, but he had greatly dared'.[a] His sisters came to weep for him and were transformed into poplar trees on the banks of the Eridanus.  Forever, they weep, and each tear that falls into the river shines like amber.\n\n"+
			  "REFERENCES\n\n"+
              "a. Mythology. Hamilton, Edith. Warner Books Edition. 1271 Avenue of the Americas, New York, NY, 10020. 1942"
};