var indiaInfo = {
	indiaMyth: "",
	gurudrahTitle: "Gurudrah and Shiva",
	gurudrah: "It begins in a forest.  The hunter Gurudruh waiting patiently to see what had caused the leaves to rustle.  Nothing was to be seen, must've been a burrowing animal.  After holding his bow drawn and ready for some time, he slowly released the tension on the string and set it to rest.  It was time to move to another spot, and so he did.  As he moved through the forest he chanting and followed it to a temple where the people were chanting 'Shiva, Shiva, Om Namah Shivaya, Shiva, Shiva'[a].  Gurudruh was intrigued, but knew he must continue his work to gather food for his family.\n\n"+
              "Soon he realized he had never been so deep into this forest.  However, to his great joy he soon came across a pond.  'A perfect place to hunt', he thought to himself, as surely many animals would come to drink from the pond.  He sought a place to wait, and so he climbed a tree close to the pond, but to his dismay a branch slashed his water pouch and soon he found all his water leaking from it; however, he found comfort in the fact he was so close to a pond.  Gurudruh reminisced about the scene and words at the temple.  He thought to himself that the people were fools to worship someone more powerful than them, and so he decided he would do the opposite and so he began speaking 'Vashi, Vashi' [a].  Soon he heard rustling, and slowly began removing leaves from the tree that were blocking his view so he could see in order to shoot his possible prey.\n\n"+
              "Soon he saw the silhouette of a deer.  Then he saw the full deer and noticed how beautiful it was.  He knocked an arrow and drew back his bow, ready to release and take the deer down.  Then the deer spoke!  It said, 'Please don't kill me hunter', and went on to explain '...I am the mother of a young deer and I am looking for it and my husband.  Once I find them I will come back and let you kill me' [a].  Gurudruh reluctantly agreed to let the deer go, and somehow found the trust that it would return.  Soon another deer arrived, and it also spoke.  It explained to Gurudruh, as he held his drawn bow ready to fire, that he was the husband of the female deer and father of the young one.  This deer made the same promise, '...let me find my wife and young one, and I will return for you to kill me...'.  Both time Gurudruh thought he was crazy to let them go, but he did anyway.\n\n"+
              "While Gurudruh waited in the tree he continued muttering 'Vashi, Vashi' to pass the time.  Then another deer showed up at the pond.  Gurudruh had decided this would be the one, he would shoot regardless, and then the deer spoke.  She explained she was the sister of the other two deer, and she had found their young son and asked him not to shoot her so she could let the others know she had found him.  If she did not tell them, they would never have any peace.  So, while he wanted to put a hole in something, Gurudruh once again released the resistance on the string and did not fire.\n\n"+
              "This all took place in one night, and soon that night was coming to an end.  As he watched the pond, four deer soon came into sight.  The father deer expressed his gratitude to Gurudruh and explained they had all performed their duties, all because Gurudruh had let them go.  Now they offered their lives into his hands [a].  Each deer in turn said for Gurudruh to kill them, if he killed the others so they could remain together.  At this point Gurudruh realised these were no ordinary deer.  He leapt from the tree and ran to the deer.  He expressed that he knew they were not deer, and asked who it was that stood in front of him.  Then all four deer vanished, and in their place stood '...a beautiful three eyed god' [a].  Upon seeing him, Gurudruh felt a strong feeling of bliss, and freedom.\n\n"+
              "The god, Shiva, told Gurudruh that the worship he had given was more than any other ever had.  Gurudruh was confused as he had done nothing to worship.  Then Shiva explained that Gurudruh had given him water, offered his favorite leaves, and fasted for the entire night.  Gurudruh suddenly realized the tree was the 'bliva' tree, which holds Shiva's favorite leaves.  At the bottom of the tree was the linga, which was wet from his water pouch and covered in the leaves he had removed in order to see.  Also, as he was repeating 'Vashi, Vashi' it soon became 'Shiva, Shiva'.  For his worship, though unknown to him, Shiva blessed him and gave him a spot in his world, and so Gurudruh followed Shiva back to Kailash.\n\n"+
              "REFERENCES:\n\n"+
			  "a. The Salvation of Grurdruh. sakrishnan. hindumythologyforgennext.blogspot.com. 01/01/2012. http://hindumythologyforgennext.blogspot.com/search/label/Stories%20of%20Shiva"
};