var norseInfo={
	norseMyth: "",
	odinTitle: "Odin on the Tree",
	odin: "This story comes after Odin sacrifices his eye at the well of Mimir for wisdom.  It is his retelling of how he hanged himself from Yggdrasil for nine nights, pierced by Gungnir (his spear),"+
          "sacrificing himself to himself, and learned of eighteen charms.  Kevin Crossley-Holland's [a] version begins by describing Yggdrasil itself, and the creatures which inhabit it.  It follows the tree's roots all the way"+
          "to Niflheim, describes the serpent Nidhogg, the squirrle Rattatosk, and the eagle at the top which has a hawk perched on its brow.  It tells of how Nidhogg feeds on corpses, and offers "+ 
          "insults to the eagle which are delivered by Rattatosk.  There are deer and other animals which eat the leaves and foliage of the world tree.\n\n"+
          "After describing the tree, the creatures, and the worlds to which the roots run the story goes on as a monologue of Odin.  In this he describes how he approached the tree alone, hanged "+
          "himself from it, stabbed by Gungnir, and describes the charms which he learned.  The charms totaled 18:\n\n"+
		  "1.  Offers comfort in grief and heals pains and sicknesses\n"+
		  "2.  A healing charm, as it says that a healer needs to know it\n"+
		  "3.  Blunts steel and softens wood so as to be safe from harm\n"+
		  "4.  Breaks bounds and chains\n"+
		  "5.  Allows the stopping of missiles in mid air, no matter their speed\n"+
		  "6.  A counter-spell, if you will. Runes to destroy Odin will only destroy the deliverer\n"+
		  "7.  Puts out fire, no matter how hot\n"+
		  "8.  Ability to uproot hatred from the hearts of men\n"+
		  "9.  Calm the wind and seas\n"+
		  "10. A song to stop witches from returning home or to there day time selves\n"+
		  "11. Keep brothers safe in battle so they go to, participate in, and return home from battle safely\n"+
		  "12. Ability to speak with the dead\n"+
		  "13. Sprinkle child with water and that child will perform great in battle and never misswing his sword\n"+
		  "14. Speak the names of all gods and elves\n"+
		  "15. Song of power to the gods, knowledge to Odin, and glory for the elves\n"+
		  "16. Make women fall in love\n"+
		  "17. Another love charm\n"+
		  "18. Your own knowledge is the greatest\n\n"+
		  "REFERENCES\n\n"+
          "a. The Norse Myths. Crossley-Holland, Kevin. Pantheon Books, NY 1980. pages 15-17 (Notes 186-188)\n"+
          "b. God of the Gallows... ancientpages.com. May 7, 2018. http://www.ancientpages.com/2018/05/07/god-of-the-gallows-and-how-odin-hanged-himself-from-yggdrasil-to-know-secrets-of-runes/",
	skirnirTitle: "The Journey of Skirnir",
	skirnir: "The story begins with Freyr sitting in Odin's hall, Valaskjalf and upon his chair Hlidskjalf.  The chair was only the right of Odin and Frigg, but Freyr dared to sit anyway and look over the nine worlds.  From there he sees the giantess Gerd leaving her father's hall.  It was as if she was made of light, and as she opens the door the brightness envelopes the nine worlds.  Freyr was love struck, and delved into a depression.  From that point it was only having Gerd of which Freyr thought.  He couldn't bear to be without her and to that end he would not eat, drink, or speak to anyone.  Njord, Freyr's father was worried and commanded Freyr's servant, Skirnir, to find out what was troubling his son.  Freyr told Skirnir of his troubles and asked Skirnir to go and retrieve Gerd, whatever it may take.  Skirnir agrees, but asks for Freyr's horse '...which follows its nose through the dark, and will not bridle at magic, flickering flames' as well as his sword that '...fights giants of its own will...' [a].  These were given to Skirnir, and so he began his journey.\n\n"+
             "Skirnir rode throughout the night.  The horse did not slow down, even for the pillars of flame it had to pass.  Finally, Skirnir came into a desolate land where nothing grew and found Gerd's hall.  The hall was guarded by two ferocious dogs, and Skirnir found Gerd's watchman and asked how he could pass the dogs.  The watchman told him there was no way, but Skirnir wheeled about and believing his fate and date of death were already decided proceeded with a determination to pass the dogs and enter the hall.  Gerd spoke with her watchman, and believing that Skirnir was the one that killed her brother, allowed him to enter the hall (no doubt with ill-intent).\n\n"+
             "Gerd asks Skirnir if he is a god or elf (for how else could he pass the curtains of fire), and Skirnir replies that he is neither elf or god.  He then offers Gerd eleven golden apples of youth, in return for her going to Freyr.  She declines.  He offers her Draupnir, an arm ring that every ninth night creates eight other rings equal to itself.  She declines.  Skirnir then turns to force, and tells Gerd that he will remove her head with the sword.  When she still declines he turns his threat to her father.  When that still failed to sway her, he raised his magic staff.  He threatened to touch her with it, which would in turn cause her to never have love, be tormented forever, only be able to drink piss, and Hrimgrimnir a frost giant of disrepute would be the only to have her, among other threats.  This terrifies Gerd and she consents.\n\n"+
             "Skirnir asks her when and where she will meet with Freyr.  She says in nine days, in the forest of Barri.  Skirnir heads home with the news.  When he arrives and dismounts Freyr insists on knowing the details, even before Skirnir has unbridled his horse.  Skirnir tells him in nine days he will have Gerd in the forest of Barri.  Freyr is lament and says, 'One night is long...two nights are longer still.  How can I bear three?...' [a].  He says that a month has been shorter than one night before he had this desire in his heart.\n\n"+
             "REFERENCES:\n\n"+
			 "a. The Norse Myths. Crossley-Holland, Kevin. Pantheon Books, NY 1980. pages 54-58 (Notes 199-200)",
	njordTitle: "Njord and Skadi",
	njord: "Skadi was in Thrymheim, the storm home of her father.  Shortly, before this story Thiazi, Skadi's father, had forced Loki to help him kidnap Idun and her apples.  Loki then stole Idun back, and Thiazi chased him to Asgard where the gods dispatched him.  Skadi felt this in her heart as it had been several days, and her father had yet to return.  She grew angry and furious, swearing vengeance on those who had killed her father.  To this end Skadi dressed for battle.  She donned a coat of mail, a helmet, and chose her father's finest weapons.  Then she set out for Asgard, and revenge.\n\n"+
           "The gods were at peace and happy to have Idun back with them.  As Skadi approached the walls Heimdall sounded his horn, and the alerted the gods.  They did not wish to see any more blood spilled, and so asked Skadi if she would take money for her father's death.  She declined saying she has plenty because her father was rich, and what was his is now hers.  So the gods asked her what she would take, and she said 'A husband...and a belly full of laughter' [a pg.45].  She had her eyes set on Balder, the fairest of the gods.  The gods decided to allow her to choose a husband, but set a condition, she must choose him by his feet.\n\n"+
           "The gods lined up, and Skadi's eyes were blocked from seeing anything aside from their feet.  Finally, she came across the best looking feet.  She thought to herself that surely it was balder, after all the fairest god should have the fairest feet.  However, when she lifted her eyes and saw whom she had chosen it was Njord, lord of the sea.  Skadi begrudgingly accepted her choice, and quickly reminded the gods that also demanded laughter.\n\n"+
           "None other than Loki, was chosen to perform the task of jester.  He chose to tell Skadi a story of how he went to the market with his goat.  He had to tie his goat up to something to keep it from running away, and for this he chose his testicles.  So, he proceeded with the story, of how he was standing there and goat began to move away (he demonstrated this as he told it).  He and the goat began a tug of war, and soon the goat gave way and Loki bound haphazardly into the arms of Skadi, who could not help but laugh at the sight.  Odin added another gift to the bundle, and tossed Thiazi eyes into the sky, creating two stars to always look down on his daughter.\n\n"+
           "Njord asked Skadi to stay with him in his hall, and she rebutted that he should stay with her in Thrymheim.  Neither desired to stay for ever in the other's hall and so they came to the agreement that for nine nights they would be in one place, and for nine nights they would be in the other.  Njord went with Skadi to Thrymheim to start.  It was cold and full of ice.  Almost lifeless, and yet Skadi's happiness grew as they approached, while Njord's dwindled.  Then they went to live in Noatun, Njord's hall, where the ships come in to anchor and the sea birds fly all day.  Skadi, could not stand this place.  It was too loud for her, and with too much activity.  They soon decided that although they were married, they could not live together, and so Skadi returned to Thrymheim and Njord stayed in Noatun.  It says that Skadi '...took injury and death wherever she went.  She had been touched by the god of plenty; she had yielded a little, and then frozen again' [a pg.47].\n\n"+
           "REFERENCES:\n\n"+
		   "a. The Norse Myths. Crossley-Holland, Kevin. Pantheon Books, NY 1980. pages 44-47 (Notes 199-200)"
};